# Generated by Django 4.1 on 2022-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
