# Generated by Django 4.1 on 2022-08-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
