# Generated by Django 4.1 on 2022-08-19 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_ingridentnames_post_ingrident_post_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrident', models.CharField(choices=[('salt', 'Salt'), ('sugar', 'Sugar'), ('flour', 'Flour'), ('turmeric', 'Turmeri'), ('cocopowder', 'Coco Powder'), ('milk', 'Milk'), ('bakingpowder', 'Baking Powder')], max_length=50, null=True)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=5)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrident', to='base.post')),
            ],
        ),
    ]
