# Generated by Django 4.1 on 2022-08-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_ingrident'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingrident',
            new_name='RecipeIngrident',
        ),
    ]
