# Generated by Django 4.1 on 2022-08-19 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_ingrident_recipeingrident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingrident',
            name='ingrident',
        ),
        migrations.AddField(
            model_name='recipeingrident',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='base.ingridentnames'),
            preserve_default=False,
        ),
    ]
