# Generated by Django 4.1 on 2022-08-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_recipeingrident_ingrident_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridentnames',
            new_name='Ingrident',
        ),
        migrations.RemoveField(
            model_name='recipeingrident',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='recipeingrident',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrident', to='base.post'),
        ),
    ]
