# Generated by Django 4.1 on 2022-08-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_ingridentnames_ingrident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingrident',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='base.ingrident'),
        ),
    ]
