# Generated by Django 4.1 on 2022-08-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_recipeingrident_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingrident',
            name='ingredient',
            field=models.CharField(choices=[('salt', 'Salt'), ('sugar', 'Sugar'), ('flour', 'Flour'), ('turmeric', 'Turmeri'), ('cocopowder', 'Coco Powder'), ('milk', 'Milk'), ('bakingpowder', 'Baking Powder')], max_length=50, null=True),
        ),
    ]
