# Generated by Django 4.1 on 2022-08-20 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0022_alter_post_likes_alter_post_unlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='recipe_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='unlike_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipeingrident',
            name='ingredient',
            field=models.CharField(choices=[('salt', 'Salt'), ('sugar', 'Sugar'), ('flour', 'Flour'), ('turmeric', 'Turmeri'), ('cocopowder', 'Coco Powder'), ('milk', 'Milk'), ('bakingpowder', 'Baking Powder')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
