# Generated by Django 4.1 on 2022-08-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_post_likes_alter_post_unlikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingrident',
            name='ingredient',
            field=models.CharField(choices=[('salt', 'Salt'), ('sugar', 'Sugar'), ('flour', 'Flour'), ('turmeric', 'Turmeric'), ('cocopowder', 'Coco Powder'), ('milk', 'Milk'), ('bakingpowder', 'Baking Powder')], max_length=50),
        ),
    ]
