# Generated by Django 4.1 on 2022-08-21 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0024_alter_recipeingrident_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='recipe_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlikes',
            field=models.ManyToManyField(related_name='unlike_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipeingrident',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingrident', to='base.ingrident'),
        ),
    ]
